### ISSUE TITLE
charset_normaliser module contains Intel Mach O shared libraries

### ISSUE THREAD

**Issue by BigW72** [BenjaminOddou/alfred-plex#2]
This workflow wouldn't run on my M2 Mini. Debugging showed that the problem appears to be that the included charset_normaliser package includes Intel versions of `md.cpython-311-darwin.so`  and `md__mypyc.cpython-311-darwin.so`

Error message:

```
Traceback (most recent call last):
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/search_entry.py", line 4, in <module>
    from lib.plexapi.server import PlexServer
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/lib/plexapi/__init__.py", line 8, in <module>
    from plexapi.config import PlexConfig, reset_base_headers
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/plexapi/__init__.py", line 10, in <module>
    from plexapi.utils import SecretsFilter
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/plexapi/utils.py", line 19, in <module>
    import requests
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
ImportError: dlopen(<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/md.cpython-311-darwin.so, 0x0002): tried: '<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/md.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/md.cpython-311-darwin.so' (no such file), '<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/./lib/charset_normalizer/md.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/lib/charset_normalizer/md.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/lib/charset_normalizer/md.cpython-311-darwin.so' (no such file), '<Alfred folder>/Alfred.alfredpreferences/workflows/user.workflow.<UUID>/lib/charset_normalizer/md.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
``` 

My workaround was to manually install `charset_normaliser` over the existing one by executing:

```
 pip install charset-normalizer -t ./lib
```

from the folder where the Alfred Plex workflow is installed.

I don't know enough about Python packaging to propose a proper fix.

**Comment by BenjaminOddou** [comment]
Hello @BigW72, thanks for the feedback. You're not the first to report an issue with `charset-normalizer`. I don't have a mac with a silicon chip so it's hard to reproduce on my side. I will try to see if I can embedded `arm` compatibles files as well. I let this issue open for now.

**Comment by BenjaminOddou** [comment]
Hello @BigW72, could you try to run the following command in the workflow folder to see if it's working ? I think the `.so` shared libraries aren't really needed.

```shell
pip3 install plexapi -t lib --platform macosx-10.9-x86_64 --only-binary=:all: --upgrade
```

**Comment by BigW72** [comment]
> Hello @BigW72, could you try to run the following command in the workflow folder to see if it's working ? I think the `.so` shared libraries aren't really needed.
> 
> ```shell
> pip3 install plexapi -t lib --platform macosx-10.9-x86_64 --only-binary=:all: --upgrade
> ```

I deleted the workflow in Alfred and reinstalled it. After reinstallation I got the same error as before. After reinstalling `plexapi` in the `lib` folder as you suggested it worked.

My platform is
```
>>> import platform
>>> platform.platform()
'macOS-13.2.1-arm64-arm-64bit'
```

I then deleted the workflow again, reinstalled `plexapi` but without the `--platform` argument and it still worked.

**Comment by BenjaminOddou** [comment]
Ok that's great. However, if you don't specify the `--platform`, `pip` will install binaries depending on your config(that's why it's working even without the `--platform`):

```shell
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp311-cp311-macosx_10_9_x86_64.whl (123 kB)
```

What we need is :

```shell
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
```

to be platform agnostic. I'll drop a fix very soon. I'll let you come back to me in case of problems after the fix.
